# Materia Dark (PapirusDevelopmentTeam/materia-kde)
background            #181818
foreground            #eff0f1
cursor                #eff0f1

selection_background  #ffffff
selection_foreground  #2d2c2d

color0                #181818
color1                #e14245
color2                #55ba79
color3                #f67400
color4                #4285f4
color5                #9b59b6
color6                #1abc9c
color7                #eff0f1
color8                #7f8c8d
color9                #c0392b
color10               #00c853
color11               #fdbc4b
color12               #6aa6f4
color13               #8e44ad
color14               #16a085
color15               #fcfcfc
