# https://wiki.hyprland.org/Configuring/Keywords/

$terminal = kitty
$fileManager = dolphin
$menu = tofi-drun -c ~/.config/tofi/configA --drun-launch=true
$browser = firefox
$editor = code
$colorPicker = hyprpicker

$mainMod = SUPER # Sets "Windows" key as main modifier