# https://wiki.hyprland.org/Configuring/Monitors/

monitor=eDP-1,preferred,auto,1.5
monitor=DP-4,preferred,auto,1
monitor=DP-5,preferred,auto,1,transform,1

workspace=1,monitor:eDP-1
workspace=2,monitor:eDP-1
workspace=3,monitor:DP-4
workspace=4,monitor:DP-4
workspace=5,monitor:DP-4
workspace=6,monitor:DP-4
workspace=7,monitor:DP-5
workspace=8,monitor:DP-5
workspace=9,monitor:DP-5
workspace=10,monitor:DP-5
