$src = ~/.config/hypr/hyprland_configs

# https://wiki.hyprland.org/Configuring/Monitors/
source = $src/monitor.conf

# https://wiki.hyprland.org/Configuring/Keywords/
source = $src/keyword.conf

# https://wiki.hypr.land/Configuring/Keywords/#executing
source = $src/exec.conf

# https://wiki.hyprland.org/Configuring/Environment-variables/
source = $src/env.conf

# https://wiki.hyprland.org/Configuring/Variables/
source = $src/configuring_variables.conf

# https://wiki.hyprland.org/Configuring/Binds/ 
source = $src/binds.conf

# TODO: add hyprland documentation link
source = $src/layout.conf
